site_name: WorkWiki
nav:
  - Главная: index.md
  - Анкеты регистрации:
      - registration/index.md
      - registration/Регистрационная форма - без буфера и без динамического добавления (новое).md
      - registration/Регистрационная форма - без буфера с динамическим добавлением.md
      - registration/Регистрационная форма - с буфером без динамического добавлениея.md
      - registration/Регистрационная форма - с буфером и с динамическим добавлением.md
  - Wizard:
      - Wizard/index.md
      - Wizard/Wizard - добавление кнопок для изменения статусов кураторам в ЛК.md
      - Wizard/Wizard - необязательное добаление файла.md
      - Wizard/Wizard - переключатели (ветвление) формы подачи документов.md
  - Письма и Рассылки:
      - post/index.md
      - post/Письма - отправка писем о регистрации если не основной участник.md
      - post/Рассылки.md
theme:
  name: material
  features:
    - navigation.tabs
    - search