site_name: WorkWiki
nav:
  - Главная: index.md
  - Анкеты регистрации:
      - registration/index.md
      - registration/Регистрационная форма - без буфера и без динамического добавления (новое).md
      - registration/Регистрационная форма - без буфера с динамическим добавлением.md
      - registration/Регистрационная форма - с буфером без динамического добавлениея.md
      - registration/Регистрационная форма - с буфером и с динамическим добавлением.md
      - registration/Дополнительные параметры.md
  - Wizard:
      - Wizard/index.md
      - Wizard/Wizard - добавление кнопок для изменения статусов кураторам в ЛК.md
      - Wizard/Wizard - необязательное добаление файла.md
      - Wizard/Wizard - переключатели (ветвление) формы подачи документов.md
      - Wizard/bindings.md
  - Письма и Рассылки:
      - post/index.md
      - post/Письма - отправка писем о регистрации если не основной участник.md
      - post/Рассылки.md
  - Ссылки:
      - links/index.md
      - links/Ссылка на регистрацию в формате личного кабинета.md
  - Опросы:
      - survey/index.md
      - survey/Создания ветвления в опросе.md
  - Согласия:
      - consents/index.md
      - consents/Старое - Согласие на ОПД.md
      - consents/Старое - Согласие на фото-видео.md
      - consents/Старое - Согласие на правила поведения.md
      - consents/Старое - Согласие на медвмешательство.md
      - consents/Старое - Согласие на виды активности.md
      - consents/Договор с помесячной оплатой.md
      - consents/Договор-оферта.md
      - consents/Новое - Согласие на медвмешательство.md
      - consents/Новое - Согласие на фото-видео.md
      - consents/Новое - Согласие на ОПД.md
  - Ошибки:
      - errors/index.md
      - errors/Ошибка - формирование счета на оплату в личном кабинете - нарушение связи договора.md
theme:
  name: material
  features:
    - navigation.tabs
    - search